### ISSUE TITLE
static assert message is lying

### ISSUE THREAD

**Issue by PeterSommerlad** [barneydellar/SpaceTypes#12]
```C++
if (l.size() != 3)
            {
                throw std::invalid_argument("You can only initialise with two elements");
            }
```

**Comment by barneydellar** [comment]
Thanks! I've added tests and fixed this.

**Comment by PeterSommerlad** [comment]
The magic constant 3 is pervasive in the code. You might consider centralizing it, but it also might not be worth it....

**Comment by barneydellar** [comment]
Yeah, I did consider generalising for n-dimensional spaces... But it wasn't my use-case, so I didn't.

**Comment by PeterSommerlad** [comment]
not over generalizing is a good decision. one more question: why the initializer_list constructor at all?  you have the three element constructor that can be used with {1,2,3}

Please educate me!

**Comment by barneydellar** [comment]
Yeah, if I remove the initializer_list constructor, then this still works: 
```
View::Point p{ 1, 2, 4 };
```

But unfortunately this doesn't:
```
const std::vector<View::Point> points{
    {1, 1, 1},
    {2, 2, 2}
};
```

**Comment by PeterSommerlad** [comment]
But that is only, because you made the other constructor explicit and the initializer_list constructor not.

https://godbolt.org/z/K1b939EWj

**Comment by barneydellar** [comment]
Doh! Yes, you're right. Thank you! Fixed now.

**Comment by PeterSommerlad** [comment]
You are welcome. I use the term "decremental development" in my conference talks: Make code simpler by refactoring. Down to 10% its size with better tests and functionality. Can I reach you on email for further discussions? I am peter.cpp@sommerlad.ch
